"""empty message

Revision ID: 511dce4920c7
Revises: 4fe4d0510506
Create Date: 2024-12-23 22:10:14.037853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511dce4920c7'
down_revision = '4fe4d0510506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('city')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
